insert into User_Emp(user_id, name, email_address, contact_no, date_of_birth, user_type, password) values('venkat', 'Venkat', 'venkat@gamil.com', 7894561230, '1978-07-27', 'Member', 'Venkat@123');
insert into User_Emp(user_id, name, email_address, contact_no, date_of_birth, user_type, password) values('rajini', 'Rajini', 'rajini@gamil.com', 7894561231, '1968-08-01', 'Admin', 'Rajini@123');
insert into User_Emp(user_id, name, email_address, contact_no, date_of_birth, user_type, password) values('vinay', 'Vinay', 'vinay@gamil.com', 7894561232, '1987-12-19', 'Admin', 'Vinay@123');


insert into project(project_id, project_description, project_start_date, project_end_date, project_manager_email_id, project_manager_name, project_name, remarks, status, tech_lead_email_id, tech_lead_name, team_name, team_size, tech_stack) values('project1', 'As Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', '2022-07-27', '2022-09-27', 'shekar@gmail.com', 'shekar', 'project1', 'pending', 'ongoing', 'ram@gmail.com', 'Ram', 'Team1', '3', 'stack1');
insert into project(project_id, project_description, project_start_date, project_end_date, project_manager_email_id, project_manager_name, project_name, remarks, status, tech_lead_email_id, tech_lead_name, team_name, team_size, tech_stack) values('project2', 'TAs Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', '2022-06-18', '2022-10-29', 'srikar@gmail.com', 'srikar', 'project2', 'pending', 'hold', 'ram@gmail.com', 'Ram', 'Team2', '3', 'stack1');
insert into project(project_id, project_description, project_start_date, project_end_date, project_manager_email_id, project_manager_name, project_name, remarks, status, tech_lead_email_id, tech_lead_name, team_name, team_size, tech_stack) values('project3', 'As Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', '2022-07-27', '2022-10-29', 'ranga@gmail.com', 'Ranga', 'project3', 'pending', 'ongoing', 'ram@gmail.com', 'Ram', 'Team3', '3', 'stack1');
insert into project(project_id, project_description, project_start_date, project_end_date, project_manager_email_id, project_manager_name, project_name, remarks, status, tech_lead_email_id, tech_lead_name, team_name, team_size, tech_stack) values('project4', 'As Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', '2022-07-27', '2022-10-29', 'ranga@gmail.com', 'Ranga', 'project4', 'pending', 'ongoing', 'sri@gmail.com', 'Sri', 'Team4', '3', 'stack1');
insert into project(project_id, project_description, project_start_date, project_end_date, project_manager_email_id, project_manager_name, project_name, remarks, status, tech_lead_email_id, tech_lead_name, team_name, team_size, tech_stack) values('project5', 'As Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', '2022-07-27', '2022-10-29', 'ranga@gmail.com', 'Ranga', 'project5', 'pending', 'ongoing', 'ram@gmail.com', 'Ram', 'Team5', '3', 'stack1');
insert into project(project_id, project_description, project_start_date, project_end_date, project_manager_email_id, project_manager_name, project_name, remarks, status, tech_lead_email_id, tech_lead_name, team_name, team_size, tech_stack) values('project6', 'As Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', '2022-07-27', '2022-10-29', 'ranga@gmail.com', 'Ranga', 'project6', 'pending', 'ongoing', 'srikanth@gmail.com', 'Sri Kanth', 'Team6', '3', 'stack1');


insert into story(story_id, assignee, assignment_date, assignee_email_id, project_id, remarks, status, story_description, story_title, target_date) values('story1', 'Rajan', '2022-07-27', 'rajan@gmail.com', 'project1', 'pending', 'ongoing', 'As Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', 'Story1', '2022-09-27');
insert into story(story_id, assignee, assignment_date, assignee_email_id, project_id, remarks, status, story_description, story_title, target_date) values('story2', 'Hari Krishna', '2022-06-18', 'harikrishna@gmail.com', 'project2', 'pending', 'hold', 'As Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', 'Story2', '2022-10-29');
insert into story(story_id, assignee, assignment_date, assignee_email_id, project_id, remarks, status, story_description, story_title, target_date) values('story3', 'Rajan', '2022-07-27', 'rajan@gmail.com', 'project3', 'green', 'ongoing', 'As Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', 'Story3', '2022-09-07');
insert into story(story_id, assignee, assignment_date, assignee_email_id, project_id, remarks, status, story_description, story_title, target_date) values('story4', 'Rajan', '2022-07-27', 'rajan@gmail.com', 'project3', 'green', 'ongoing', 'As Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', 'Story3', '2022-09-07');
insert into story(story_id, assignee, assignment_date, assignee_email_id, project_id, remarks, status, story_description, story_title, target_date) values('story5', 'Rajan', '2022-07-27', 'rajan@gmail.com', 'project3', 'green', 'ongoing', 'As Bean Validation API is just a specification, it requires an implementation. So, for that, it uses Hibernate Validator. The Hibernate Validator is a fully compliant.', 'Story3', '2022-09-07');

